config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  get "/sign-up", to: "users#new", as: "sign_up"
  post "/sign-up", to: "users#create"

  get "/sign-in", to: "sessions#new", as: "sign_in"
  post "/sign-in", to: "sessions#create"

  get "/sign-out", to: "sessions#destroy", as: "sign_out"

  get "/dashboard", to: "users#show", as: "dashboard"

  resources :pools, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/membership.rb
class Membership < ApplicationRecord
  belongs_to :pool
  belongs_to :user

  validates :user_id, uniqueness: { scope: :pool_id }
end

app/models/option.rb
class Option < ApplicationRecord
  belongs_to :question
end

app/models/pool.rb
class Pool < ApplicationRecord
  TYPES = { "Prop Bets" => 0 }
  belongs_to :super_admin, class_name: "User", foreign_key: :user_id

  has_many :admin_memberships, -> { where(role: 1) }, class_name: "Membership"
  has_many :admins, through: :admin_memberships, source: :user
  has_many :member_memberships, -> { where(role: 0) }, class_name: "Membership"
  has_many :members, through: :member_memberships, source: :user
  has_many :questions

  enum game: [:prop_bet]

  def all_members
    admins + members
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :pool
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, presence: true, uniqueness: { case_sensitive: false }

  has_many :pools
  has_many :admin_memberships, -> { where(role: 1) }, class_name: "Membership"
  has_many :admin_pools, through: :admin_memberships, source: :pool

  has_many :member_memberships, -> { where(role: 0) }, class_name: "Membership"
  has_many :member_pools, through: :member_memberships, source: :pool

  def all_admin_pools
    pools + admin_pools
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit::Authorization

  helper_method :current_user

  private

  def redirect_user
    redirect_to dashboard_path if current_user
  end

  def require_user
    flash[:alert] = "Sign in to view this path"
    redirect_to sign_in_path unless current_user
  end

  def current_user
    @current_user ||= User.includes(:pools, :admin_pools, :member_pools).find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :require_user, only: [:new, :create]

  def show
    @pool = Pool.includes(:admins, :members).find(params[:id])
    authorize @pool
  end

  def new
    @pool = current_user.pools.new
  end

  def create
    @pool = Pool.new(pool_params.merge(user_id: current_user.id))
    if @pool.save
      flash[:notice] = "Pool created!"
      redirect_to @pool
    else
      flash[:alert] = @pool.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def pool_params
    params.require(:pool).permit(:name, :game, :active, :locked, :finalized, :archived)
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :require_user

  def create
    @pool = Pool.find(params[:pool_id])
    @question = @pool.questions.new(question_params)
    @question.errors.add(:number_of_options, "less than 2 options") if @question.options.size < 2
    if @question.errors.empty? && @question.save
      flash[:notice] = "Your question has been created"
    else
      flash[:alert] = @question.errors.full_messages.join(", ")
    end
    redirect_to @pool
  end

  private

  def question_params
    params.require(:question).permit(:description, :tiebreaker, options_attributes: [:description])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_user, except: [:destroy]
  before_action :require_user, only: [:destroy]

  def create
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      flash[:notice] = "Welcome!"
      redirect_to dashboard_path
    else
      flash[:alert] = "Something went wrong"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "See you later!"
    redirect_to sign_in_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user, only: [:show]
  before_action :redirect_user, only: [:new, :create]

  def show
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Created and signed in!"
      redirect_to dashboard_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation, :nickname)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div>
  <h1 class="font-bold text-4xl">Home#index</h1>
  <p>This is the root path</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PropBets</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@1.*/css/pico.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <main class="container">
      <%= render partial: "shared/navbar" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pools/_pool.html.erb
<li><%= link_to pool.name, pool %></li>

app/views/pools/_pool_form.html.erb
<%= form_with model: @pool do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :lock %>
  <%= f.datetime_select :lock %>

  <%= f.label :finalize %>
  <%= f.datetime_select :finalize%>

  <%= f.label :multiple_entries do %>
    <%= f.check_box :multiple_entries %>
    Allow multiple entries per person?
  <% end %>

  <%= f.submit %>
<% end %>

app/views/pools/edit.html.erb
<%= render partial: "pool_form" %>

app/views/pools/new.html.erb
<%= form_with model: @pool do |f| %>
  <%= f.label :name, "Name" %>
  <%= f.text_field :name %>
  <%= f.label :game, "Game Type" %>
  <%= f.select :game, options_for_select(Pool.games.map{ |k,v| [k.titleize, Pool.games.key(v)]}, @pool.game) %>
  <div>
    <%= f.label :public_pool do %>
      <%= f.check_box :public_pool %>
      Publicly viewable?
    <% end %>
  </div>

  <%= f.submit "Create Pool" %>
<% end %>

app/views/pools/show.html.erb
<%= @pool.name %>

app/views/shared/_navbar.html.erb
<nav>
  <ul>
    <li>PROP<strong>BETS</strong></li>
  </ul>
  <ul>
    <% if current_user %>
      <li><%= link_to "Dashboard", dashboard_path %></li>
      <li><%= link_to "Sign Out", sign_out_path, role: "button" %></li>
    <% else %>
      <li><%= link_to "Sign Up", sign_up_path %></li>
      <li><%= link_to "Sign In", sign_in_path %></li>
    <% end %>
  </ul>
</nav>

app/views/users/edit.html.erb
<h1>Edit profile</h1>

<%= form_with model: current_user do |f| %>
  <%= f.label :first_name %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name %>
  <%= f.text_field :last_name %>
  <%= f.label :nickname %>
  <%= f.text_field :nickname %>
  <%= f.submit "Update profile" %>
  <%= link_to "Skip this time", dashboard_path(skip: true) %>
<% end %>

app/views/users/new.html.erb
<h2>Sign Up</h2>
<%= form_with model: @user, url: sign_up_path do |f| %>
  <div>
    <%= f.label :email, "Email Address" %>
    <%= f.text_field :email %>
  </div>
  <div class="grid">
    <div>
      <%= f.label :password, "Password" %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.label :passowrd_confirmation, "Password Confirmation" %>
      <%= f.password_field :passowrd_confirmation %>
    </div>
  </div>
  <%= f.submit "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<h2>Dashboard</h2>
<%= link_to "Create Pool", new_pool_path, role: "button" %>
<hr>

<p>Welcome, <%= current_user.email %>!</p>
<h3>Pools</h3>
<div class="grid">
  <article>
    <h3>Admin Pools</h3>
    <% if current_user.all_admin_pools.any? %>
      <ul><%= render current_user.all_admin_pools %></ul>
    <% else %>
      <p>You are not currently an admin on any pools, maybe <%= link_to "create one", new_pool_path %>.</p>
    <% end %>
  </article>
  <article>
    <h3>Member Pools</h3>
    <% if current_user.member_pools.any? %>
      <ul><%= render current_user.member_pools %></ul>
    <% else %>
      <p>You are not currently a member on any pools.</p>
    <% end %>
  </article>
</div>